# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Имя')),
                ('email', models.CharField(max_length=120, verbose_name='E-mail')),
                ('message', models.TextField(max_length=350, verbose_name='Сообщение')),
                ('connected_at', models.DateTimeField(auto_now_add=True, verbose_name='Заказнно')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'ordering': ['-connected_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Имя Фамилия Отчество')),
                ('phone', models.CharField(max_length=120, verbose_name='Телефон')),
                ('email', models.CharField(max_length=120, verbose_name='E-mail')),
                ('service', models.CharField(choices=[('os', 'Интернет магазин'), ('ln', 'Лэндинг-пейдж'), ('pf', 'Портфолио'), ('ud', 'Универсальный дизайн'), ('cv', 'Увеличение конверсии'), ('sp', 'Поддержка сайта')], default='os', max_length=2, verbose_name='Услуга')),
                ('comment', models.TextField(max_length=150, verbose_name='Комментарий')),
                ('ordered_at', models.DateTimeField(auto_now_add=True, verbose_name='Заказнно')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-ordered_at'],
            },
        ),
    ]
