# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatternGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block', models.CharField(max_length=100, verbose_name='Блок')),
                ('img_1', models.FileField(blank=True, null=True, upload_to='patterns/', verbose_name='Изображение Шаблона')),
                ('img_2', models.FileField(blank=True, null=True, upload_to='patterns/', verbose_name='Изображение Шаблона')),
                ('img_3', models.FileField(blank=True, null=True, upload_to='patterns/', verbose_name='Изображение Шаблона')),
                ('img_4', models.FileField(blank=True, null=True, upload_to='patterns/', verbose_name='Изображение Шаблона')),
            ],
            options={
                'verbose_name': 'Группа шаблонов',
                'verbose_name_plural': 'Группы шаблонов',
            },
        ),
    ]
