# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_patterngroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='patterngroup',
            name='background',
            field=models.FileField(blank=True, null=True, upload_to='patterns/backgrounds/', verbose_name='Фон'),
        ),
    ]
